[package]
name = "orca_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
nix = { version = "0.30.1", features = ["user"] }
rdev = "0.5.3"
serde_json = "1.0.140"
users = "0.11.0"
winit = "0.30.11"
